### ISSUE TITLE
Experiencing ANRs since v0.4.6

### ISSUE THREAD

**Issue by ananthrajsingh** [surveysparrow/surveysparrow-android-sdk#14]
At the launch of our application we try to fire `surveySparrow.startSurvey(REQUEST_CODE)` which is resulting in a lot of ANRs with this stacktrace:
```
main (waiting):tid=1 systid=9325 
       at jdk.internal.misc.Unsafe.park(Native method)
       at java.util.concurrent.locks.LockSupport.park(LockSupport.java:211)
       at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:715)
       at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1047)
       at java.util.concurrent.Semaphore.acquire(Semaphore.java:318)
       at com.surveysparrow.ss_android_sdk.APICallTask.await(APICallTask.java:94)
       at com.surveysparrow.ss_android_sdk.SurveySparrow.startSurvey(SurveySparrow.java:179)
```

Can you look into this?

**Comment by Gokulkrishna-Raju** [comment]
@ananthrajsingh  Can you please add the part of code snippet at which you integrate SurveySparrow.startSurvey in your code !!

we couldn't reproduce the issue  !!

**Comment by ananthrajsingh** [comment]
Yes @Gokulkrishna-Raju, we are using throttling for all surveys. 
I understand that you are might not be able to reproduce, that is where stacktrace could help in giving idea what might be causing the issue.

Attaching the piece of code where we are firing the survey:
```
        val survey = SsSurvey(domain, token, params.toTypedArray())
        val surveySparrow = SurveySparrow(context as? Activity, survey)
        surveySparrow.setValidateSurveyListener { jsonObject ->
            if (jsonObject.getBoolean("active")) {
                // fire the event only if active, because that is when SS SDK launches it
                sendEvent(context, EventsConstants.EventName.SURVEY_FORM_OPENED)
            }
        }
        surveySparrow.startSurvey(REQUEST_CODE)
```

**Comment by Gokulkrishna-Raju** [comment]
Fixed, latest version is updated with the fix.
