### ISSUE TITLE
Fatal Exception: java.lang.NullPointerException in surveysparrow-android-sdk:0.4.2

### ISSUE THREAD

**Issue by Gopal-dev** [surveysparrow/surveysparrow-android-sdk#7]
Fatal Exception: java.lang.NullPointerException: Attempt to read from field 'java.lang.String e.m.a.b.f' on a null object reference in method 'android.view.View e.m.a.c.onCreateView(android.view.LayoutInflater, android.view.ViewGroup, android.os.Bundle)'
       at com.surveysparrow.ss_android_sdk.SsSurvey.getSsUrl(SsSurvey.java:60)
       at com.surveysparrow.ss_android_sdk.SsSurveyFragment.onCreateView(SsSurveyFragment.java:113)
       at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2699)
       at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:320)
       at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1199)
       at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1368)
       at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1446)
       at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1509)
       at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2637)
       at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:2589)
       at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:247)
       at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:541)
       at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:210)
       at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1457)
       at android.app.Activity.performStart(Activity.java:8259)
       at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3776)
       at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
       at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2311)
       at android.os.Handler.dispatchMessage(Handler.java:111)
       at android.os.Looper.loopOnce(Looper.java:238)
       at android.os.Looper.loop(Looper.java:357)
       at android.app.ActivityThread.main(ActivityThread.java:8089)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1026)
       
       
 Issue reported in firebase crashlytics in (Samsung, xiomi, one plus, realme etc)
 We are using surveysparrow-android-sdk:0.4.2

**Comment by Gopal-dev** [comment]
Please do the needful.

**Comment by Gopal-dev** [comment]
CC: @surveysparrow-admin @ajaysivan-ss @hemanath-ss @sachin-kumar56

**Comment by sachin-kumar56** [comment]
@Gopal-dev this issue might happen because of activity getting destroyed during screen orientation changes, we have fixed this issue in version 0.4.3 can you please upgrade to the latest version and check if this issue still exists

**Comment by Gopal-dev** [comment]
Thanks for the update, will check and let you kow.

**Comment by sachin-kumar56** [comment]
Hi @Gopal-dev since there is no reply from you I'm closing this issue for now please feel free to open the issue if the problem still persists
